@startuml

[DeepSpeech\n(Speech to Text)] as deepspeech
[Hermes LED Control\n(LED Control)] as hlc
[Mosquitto\n(MQTT broker)] as mosquitto #DeepSkyBlue
[Nano TTS\n(Text to Speech)] as nanotts
[Node-RED\n(Intent Handling)] as nodered
[Raspberry Pi\n(Single Board Computer)] as raspberrypi
[Raspbian\n(Operating System)] as raspbian
[Raven\n(Wake Word)] as raven
[Respeaker\n(Microphone)] as respeaker
[Rhasspy\n(Set of voice \nassistant services)] as rhasspy
[Snips-NLU\n(Intent Recognition)] as snipsnlu
[Zigbee2MQTT\n(Bridge from Zigbee to MQTT)] as zigbee2mqtt
[CC2531/ConBee2\n(Zigbee Adapter)] as zigbeeadapter

zigbeeadapter --- zigbee2mqtt
zigbee2mqtt -- mosquitto
mosquitto --- nodered
mosquitto --- nanotts

mosquitto --- hlc
raven - mosquitto
mosquitto - snipsnlu

rhasspy -- mosquitto
deepspeech -- mosquitto

respeaker --- rhasspy

raspbian - raspberrypi
raspberrypi -- respeaker
raspberrypi -- zigbeeadapter



@enduml